// src/modules/summaries/utils/summaryCode.js
// Frontend-only code generation for summary import/export

/**
 * Generate a unique import code for a summary
 * Format: SYN-XXXXX (5 alphanumeric characters)
 * NOTE: This function is deprecated - codes are now generated by the backend
 */
export function generateImportCode() {
    const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // Exclude confusing chars
    let code = "SYN-";
    for (let i = 0; i < 5; i++) {
        code += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return code;
}

/**
 * Validate import code format
 * Format: SYN-XXXXX (5 alphanumeric characters after SYN-)
 * Must match backend validation exactly
 */
export function isValidCodeFormat(code) {
    return /^SYN-[A-Z0-9]{5}$/i.test(code);
}

